name: Docker Image CI
on:
  push:
    branches:
      - DockerVersion
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - id: set_var
        run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/park-easy-web:${{fromJson(steps.set_var.outputs.packageJson).version}}  -t ${{ secrets.DOCKER_USERNAME }}/park-easy-web:latest .  
      - name: Publish to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/park-easy-web --all-tags
