name: Docker Image CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/park-easy-web .
      - name: Publish to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/park-easy-web